#! /usr/bin/env python3.3
import sys
import re
import collections
import operator

def main(args):
	words = collections.defaultdict(int)
	for word in read_word(sys.stdin):
		words[word] += 1
	print(words)
	sorted_words = sorted(words.items(),key=operator.itemgetter(1,0))
	for entry in sorted_words:
		print(entry[0], entry[1])


def read_word(fin):
	for line in fin:
		for word in re.findall(r"[A-Za-z']*", line):
			if word == "": continue
			else: 
				yield word

if __name__ == "__main__":
	sys.exit(main(sys.argv))
